name: Deploy Theme to Xserver

on:
  push:
    branches:
      - main # mainブランチにPushされたときに起動します

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          protocol: sftp
          local-dir: ./
          server-dir: /yamaportfolio.jp/public_html/designo.yamaportfolio.jp/wp-content/themes/designo-theme/